### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by olapola85** [kalkih/passport-appointment-bot#15]
Getting this error now

This website is not within the supported domains for this Sitekey
(Error 1415)

**Comment by robiot** [comment]
Hm. They may have disallowed localhost. If you use linux you can probably add the domain in /etc/hosts to go to 127.0.0.1

```
127.0.0.1 thedomain
```
But then the application also would need to open up the local domain

**Comment by rtwlr** [comment]
I have the same issue on windows. Any suggestions how to solve?

**Comment by robiot** [comment]
On windows you can also map hosts, but in a different way. 
When mapping bokapass.nemoq.se to 127.0.0.1 the script will stop workingm since it tries to access localhost instead of the remote server. What you would need is a mix of both - Only map bokapass.nemoq.se to localhost when the capacha is opened, else not.
```
127.0.0.1 bokapass.nemoq.se
```

**Comment by kalkih** [comment]
They have most likely restricted their mtcaptcha sitekey to only allow requests from `bokapass.nemoq.se` (which they should have done in the first place to be fair), it was nice for the 10 hours it worked 🙂

**Comment by kalkih** [comment]
Should be fixed with 963e32a7b552bc7b0eadcd89e1338c0fe8bff101

Available in the [latest release](https://github.com/kalkih/passport-appointment-bot/releases/latest)
